# Generated by Django 3.0.4 on 2020-04-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapi', '0002_auto_20200329_2227'),
        ('questionsapi', '0006_auto_20200330_0912'),
    ]

    operations = [
    ]
