# Generated by Django 3.0.4 on 2020-04-02 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionsapi', '0007_merge_20200401_1113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjects',
            unique_together={('subjectname', 'id')},
        ),
    ]
